# GridWorld

Policy Evaluation

In [2]:
import gym
import numpy as np
import sys
if "../" not in sys.path:
  sys.path.append("../") 
from lib.envs.gridworld import GridworldEnv

In [3]:
env = GridworldEnv()

In [17]:
env.P[2][2][0][2]
a = [2,3,4]
b = [1,1,1]
b = a
b


[2, 3, 4]

In [31]:
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.
    """
    # Start with a random (all 0) value function
    valueFunction = [0 for i in range(env.nS)]
    delta = 0.1
    while (delta > theta):
        vtemp = [0 for i in range(env.nS)]
        delta = 0
        for i in range (env.nS):
            temp = valueFunction[i]
            s = 0
            for a in range(env.nA):
                next_value = 0
                if(env.P[i][a][0][3]):
                    next_value = valueFunction[env.P[i][a][0][1]]
                s+= (1/4) *  env.P[i][a][0][0] * (env.P[i][a][0][2] + discount_factor * next_value)
            vtemp[i]= s
            print("state ",i, "value ", s)
            delta = max(delta, abs(vtemp[i] - temp))
            print("delta \n",delta)
        valueFunction = vtemp
    return valueFunction

In [32]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)
print(v)


[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
state  0 value  0.0
delta 
 0
state  1 value  -1.0
delta 
 1.0
state  2 value  -1.0
delta 
 1.0
state  3 value  -1.0
delta 
 1.0
state  4 value  -1.0
delta 
 1.0
state  5 value  -1.0
delta 
 1.0
state  6 value  -1.0
delta 
 1.0
state  7 value  -1.0
delta 
 1.0
state  8 value  -1.0
delta 
 1.0
state  9 value  -1.0
delta 
 1.0
state  10 value  -1.0
delta 
 1.0
state  11 value  -1.0
delta 
 1.0
state  12 value  -1.0
delta 
 1.0
state  13 value  -1.0
delta 
 1.0
state  14 value  -1.0
delta 
 1.0
state  15 value  0.0
delta 
 1.0
state  0 value  0.0
delta 
 0
state  1 value  -1.0
delta 
 0
state  2 value  -1.0
delta 
 0
state  3 